[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn build"
publish = ".next"

[[plugins]]
    package =  "@netlify/plugin-sitemap"
	[plugins.inputs]
  buildDir = ".next"
  filePath = "/sitemap.xml"
  
[[plugins]]
  package =  "netlify-plugin-submit-sitemap"
	# Time in seconds to not submit the sitemap after successful submission
	[plugins.inputs]
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]