[build]
  command = "yarn build"
  publish = ".next" # Required for Next.js 15 + Netlify

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://facebook.bocadodallas.com/*"
  to = "https://facebook.com/bocadodallas"
  status = 301
  force = true

[[redirects]]
  from = "https://shop.aztecamusicgroup.com/*"
  to = "https://azteca-music-group.myshopify.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://merch.bxsoficial.com/*"
  to = "https://bryndisxsiempre-online-shop.creator-spring.com/"
  status = 301
  force = true