import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GetServerSideProps } from "next";
import { sdkClient } from "@/lib/graphql-client";
import type { SiteLibraryQuery } from "@/graphql/generated/graphql";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps: GetServerSideProps = async () => {
  const siteLibrary: SiteLibraryQuery = await sdkClient.siteLibrary();
  return {
    props: {
      siteLibrary,
    },
  };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  { siteLibrary }: { siteLibrary: SiteLibraryQuery }
) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${siteLibrary.siteLibrary?.siteCssBodyClass}`}
      >
        {children}
        <div className="hidden h-screen  opacity-0 xl:w-3/12"></div>
        <div className="h-240 bg-white xl:w-6/12 xl:w-12/12"></div>
        <div className="h-256 opacity-0 bg-white xl:w-12/12"></div>
      </body>
    </html>
  );
}
