// import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { sdkClient } from "@/lib/graphql-client";
import type { SiteLibraryQuery } from "@/graphql/generated/graphql";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const siteLibrary: SiteLibraryQuery = await sdkClient.siteLibrary();

  return (
    <html lang="en">
      <body className={`${inter.className} ${siteLibrary.siteLibrary?.siteCssBodyClass}`}>
        {children}
      </body>
    </html>
  );
}
